version: "3"
services:
    web:
        container_name: mp_replease_platform_web
        image: mp_release_platform:2020
        ports:
            - "80:3000"
            - "443:3000"
        restart: on-failure
    mysql:
        container_name: mp_replease_platform_mysql
        restart: always
        image: mysql:5.6
        volumes:
            - ./data:/var/lib/mysql
        command: [
          '--character-set-server=utf8',
          '--collation-server=utf8_general_ci',
          --default-authentication-plugin=mysql_native_password,
        ]
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mp_release_platform
            - MYSQL_USER=mp
            - MYSQL_PASSWORD=mp2020
        ports:
            - "3306:3306"
    redis:
        container_name: mp_replease_platform_redis
        image: redis
        ports:
            - 6379:6379
